### ISSUE TITLE
Support logging UTC time

### ISSUE THREAD

**Issue by sandy081** [microsoft/node-spdlog#8]
Support logging UTC time

This need to expose setPattern API - For ref see - https://github.com/gabime/spdlog/pull/451/files

**Comment by rzhao271** [comment]
Closing this issue, because the setPattern API has already been exposed, it seems.

**Comment by bytemain** [comment]
fixed by https://github.com/microsoft/node-spdlog/pull/48

because time_type is the second argument for `setPattern` API
